### ISSUE TITLE
Needs a app installer!

### ISSUE THREAD

**Issue by develperbayman** [ghinda/oxygenos#1]
Manually inputing apps is hard and a pain
Also we appear to be the only 2 on this or just me?
Also i cannot upload git (deving on my phone)

App format should be both javascript and php (not locked to one format)
Please hit me up on hangouts developerbayman@gmail.com

**Comment by ghinda** [comment]
I'm surprised anybody is actually using this in any way. Or maybe you just posted here by mistake.

Either way, this project is ~7 years old now, and completely unmaintained, so I'm not planning on implementing a new app format, sorry.

**Comment by develperbayman** [comment]
nope no mistake right now im trying to imolement a working browser (iframe or maybe webkit.js?)

And its an android app now!

Again i dont know how to push git from my android but i would like to send you a link of what im cobbleing together

There is alot of work to get it where i would like but hey its all for fun
If your intrested :)

https://www.dropbox.com/s/ypivu3osfuhrs27/airwebos.zip?dl=0

**Comment by ghinda** [comment]
Sounds cool. Good luck!
